# Generated by Django 6.0.5 on 2026-05-15 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_business_registered', 'New Business Registered'), ('business_payment', 'Business Payment Received'), ('business_support_ticket', 'Business Support Ticket Created'), ('new_call_log', 'New Call Log'), ('new_lead', 'New Lead'), ('new_appointment', 'New Appointment'), ('meeting_reminder', 'Meeting Reminder'), ('subscription_activated', 'Subscription Activated'), ('subscription_expiry', 'Subscription Expiry Warning'), ('support_ticket_updated', 'Support Ticket Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
