# Generated by Django 6.0.5 on 2026-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
