# Generated by Django 6.0.5 on 2026-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='api_key',
            field=models.CharField(blank=True, help_text='Per-business API key for AI agent (X-API-Key header).', max_length=80, null=True, unique=True),
        ),
    ]
