# Generated by Django 6.0.5 on 2026-05-08 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_openai_key', models.TextField(blank=True, db_column='openai_key', null=True)),
                ('_deepgram_key', models.TextField(blank=True, db_column='deepgram_key', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'API Config',
                'verbose_name_plural': 'API Configs',
            },
        ),
        migrations.CreateModel(
            name='CRMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gohighlevel', 'GoHighLevel'), ('hubspot', 'HubSpot'), ('zoho', 'Zoho'), ('salesforce', 'Salesforce'), ('other', 'Other')], default='gohighlevel', max_length=50)),
                ('_token', models.TextField(blank=True, db_column='token', null=True)),
                ('_location_id', models.TextField(blank=True, db_column='location_id', null=True)),
                ('_webhook_secret', models.TextField(blank=True, db_column='webhook_secret', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'CRM Config',
                'verbose_name_plural': 'CRM Configs',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_files/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Knowledge File',
                'verbose_name_plural': 'Knowledge Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_twilio_sid', models.TextField(blank=True, db_column='twilio_sid', null=True)),
                ('_twilio_token', models.TextField(blank=True, db_column='twilio_token', null=True)),
                ('twilio_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Twilio Config',
                'verbose_name_plural': 'Twilio Configs',
            },
        ),
        migrations.CreateModel(
            name='VoiceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=20)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('voice_template', models.FileField(blank=True, help_text='Audio sample file (mp3/wav/ogg/m4a/aac/flac/webm, max 120 MB)', null=True, upload_to='voice_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Voice Config',
                'verbose_name_plural': 'Voice Configs',
            },
        ),
    ]
