# Generated by Django 6.0.5 on 2026-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRMConfig',
        ),
    ]
