# Generated by Django 6.0 on 2026-05-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the caller/lead', max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(help_text='Duration of the call (e.g., 02:30)', max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('failed', 'Failed'), ('busy', 'Busy')], default='completed', max_length=20)),
                ('call_date_time', models.DateTimeField(auto_now_add=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.business')),
            ],
            options={
                'ordering': ['-call_date_time'],
            },
        ),
    ]
