# Generated by Django 6.0 on 2026-05-15 19:58
# Modified to fix bad JSON data before altering fields

from django.db import migrations, models


def fix_bad_transcript_data(apps, schema_editor):
    """Fix transcript field that contains invalid JSON like 'AI' instead of '"AI"'"""
    CallLog = apps.get_model('call_logs', 'CallLog')

    # Count bad records
    bad_records = CallLog.objects.exclude(transcript__in=[None, ''])
    fixed = 0

    for log in bad_records:
        # If transcript is a string that's not valid JSON, clear it
        transcript = log.transcript
        if isinstance(transcript, str):
            # String like "AI" or "success" - these are not valid JSON
            # Convert to JSON string or null out
            if transcript and transcript[0] not in ('"', '[', '{'):
                # Not valid JSON, set to null
                log.transcript = None
                log.save()
                fixed += 1

    print(f"Fixed {fixed} bad transcript records")


class Migration(migrations.Migration):

    dependencies = [
        ('call_logs', '0001_initial'),
    ]

    operations = [
        # First, fix the bad data
        migrations.RunPython(fix_bad_transcript_data),

        # Then, alter the fields
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of the call (e.g., 02:30)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(blank=True, help_text='Status decided by AI', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='transcript',
            field=models.JSONField(blank=True, help_text='Conversation transcript in array format', null=True),
        ),
    ]
