# Generated by Django 6.0.5 on 2026-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
