# Generated by Django 6.0.5 on 2026-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TicketNote',
        ),
    ]
