# Generated by Django 6.0 on 2026-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_notes_delete_ticketnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
