# Generated by Django 6.0.5 on 2026-05-17 18:46

import apps.crm_integration.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crm_type', models.CharField(choices=[('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('zoho', 'Zoho CRM'), ('ghl', 'GoHighLevel'), ('pipedrive', 'Pipedrive')], max_length=20)),
                ('access_token', apps.crm_integration.models.EncryptedField()),
                ('refresh_token', apps.crm_integration.models.EncryptedField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_leads_count', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('raw_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_connections', to='accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_leads_sync', models.DateTimeField(blank=True, null=True)),
                ('last_contacts_sync', models.DateTimeField(blank=True, null=True)),
                ('total_leads_synced', models.IntegerField(default=0)),
                ('total_contacts_synced', models.IntegerField(default=0)),
                ('is_syncing', models.BooleanField(default=False)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='crm_integration.crmconnection')),
            ],
        ),
        migrations.CreateModel(
            name='CRMWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('new_lead', 'New Lead'), ('update_lead', 'Update Lead'), ('delete_lead', 'Delete Lead'), ('new_contact', 'New Contact'), ('update_contact', 'Update Contact'), ('other', 'Other Event')], max_length=50)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('crm_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='crm_integration.crmconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crm_lead_id', models.CharField(max_length=255)),
                ('crm_object_type', models.CharField(default='lead', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_leads', to='accounts.business')),
                ('crm_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_leads', to='crm_integration.crmconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmconnection',
            index=models.Index(fields=['user', 'is_active'], name='crm_integra_user_id_9d2b87_idx'),
        ),
        migrations.AddIndex(
            model_name='crmconnection',
            index=models.Index(fields=['business', 'crm_type'], name='crm_integra_busines_3d7736_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmconnection',
            unique_together={('user', 'crm_type')},
        ),
        migrations.AddIndex(
            model_name='crmwebhooklog',
            index=models.Index(fields=['crm_connection', 'processed'], name='crm_integra_crm_con_83075a_idx'),
        ),
        migrations.AddIndex(
            model_name='crmwebhooklog',
            index=models.Index(fields=['created_at'], name='crm_integra_created_cd7450_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedlead',
            index=models.Index(fields=['business', 'email'], name='crm_integra_busines_a16259_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedlead',
            index=models.Index(fields=['crm_connection', 'created_at'], name='crm_integra_crm_con_7eb46e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncedlead',
            unique_together={('crm_connection', 'crm_lead_id')},
        ),
    ]
