# Generated by Django 6.0.5 on 2026-05-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncedlead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='syncedlead',
            name='last_name',
        ),
        migrations.AddField(
            model_name='syncedlead',
            name='name',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='syncedlead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
